### ISSUE TITLE
ReferenceError: Can't find variable: React

### ISSUE THREAD

**Issue by antmaster2001** [dsernst/react-native-scrollview-offset#4]
Hi, I'm also having a problem with the content offset in react native on android. I found your npm package after reading the https://github.com/facebook/react-native/issues/6849 discussion.

After adding this to my react project I got the error: ReferenceError: Can't find variable: React, is this a problem on my side or is the package not up to date with react-native?

**Comment by dsernst** [comment]
Good question, hard to say exactly. 

I haven't used this in a while, but if I remember correctly, I was having import issues and copied the main [ScrollViewOffset.tsx](https://github.com/dsernst/react-native-scrollview-offset/blob/master/ScrollViewOffset.tsx) file directly into my directory to import it.

**Comment by antmaster2001** [comment]
Thanks for the response!

Everything is work fine now, I'm working with a horizontal page scroll,  I also had to change te useEffect invoke because my page would be set back every time.

Love the code, thank you  💯
